### ISSUE TITLE
Got an exception during open dialog

### ISSUE THREAD

**Issue by leewin12** [BasLeijdekkers/MetricsReloaded#27]
Env:
intellij 14.1.6
MetricsReloaded 1.3
Java project

Reproduce: 
Just Analyzie > Calculate Metrics and pop error up as below
`
com.sixrr.stockmetrics.DefaultMetricProvider.getMetrics()Ljava/util/List;
java.lang.AbstractMethodError: com.sixrr.stockmetrics.DefaultMetricProvider.getMetrics()Ljava/util/List;
	at com.sixrr.metrics.profile.MetricsProfileTemplate.loadMetricsFromProviders(MetricsProfileTemplate.java:77)
	at com.sixrr.metrics.profile.MetricsProfileRepository.initialize(MetricsProfileRepository.java:53)
	at com.sixrr.metrics.plugin.MetricsPluginImpl.getProfileRepository(MetricsPluginImpl.java:88)
	at com.sixrr.metrics.ui.dialogs.ProfileSelectionPanel.<init>(ProfileSelectionPanel.java:41)
	at com.sixrr.metrics.plugin.ProjectMetricsAction.getAdditionalActionSettings(ProjectMetricsAction.java:74)
	at com.intellij.analysis.BaseAnalysisAction$1.getAdditionalActionSettings(BaseAnalysisAction.java:86)
	at com.intellij.analysis.BaseAnalysisActionDialog.createCenterPanel(BaseAnalysisActionDialog.java:196)
	at com.intellij.openapi.ui.DialogWrapper.init(DialogWrapper.java:1244)
	at com.intellij.analysis.BaseAnalysisActionDialog.<init>(BaseAnalysisActionDialog.java:99)
	at com.intellij.analysis.BaseAnalysisAction$1.<init>(BaseAnalysisAction.java:82)
	at com.intellij.analysis.BaseAnalysisAction.actionPerformed(BaseAnalysisAction.java:76)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:312)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:958)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:282)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:109)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.a(BegMenuItemUI.java:512)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:44)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:532)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:565)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`

in case of 1.2.1, there is no exception like that

**Comment by BasLeijdekkers** [comment]
That's weird. What is the version of the jvm your IntelliJ IDEA is running on? (This is shown in IntelliJ IDEA's about dialog). And what is your OS?

**Comment by leewin12** [comment]
JRE: 1.8.0_51-b16 x86
JVM: Java Hotspot Server VM by oracle
OS: win7 pro K sp1

Just let me know if you need more.
your work is so awesome!! (currently I'm using 1.2.1)

**Comment by BasLeijdekkers** [comment]
It seems I uploaded a broken version 1.3 of the plugin by mistake. I uploaded a fixed 1.3.1 version, but the plugin repository decided to list it as version 1.3, so there is no update notice. Uninstalling and reinstalling MetricsReloaded should fix the problem. Let me know if you still have any problems.

Hopefully the plugin repository problem will soon be fixed.

**Comment by BasLeijdekkers** [comment]
1.3.1 is now normally available in the plugin repository. It was previously listed as 1.3 because the MetricsReloaded.jar contained 2 versions of the META-INF/plugin.xml file. The plugin repository used the first one, which was older and contained version number 1.3. IntelliJ IDEA used the last one, which was newer and contained version number 1.3.1. This caused some strange behaviour. I have fixed the build process so this particular problem can't happen again.
