### ISSUE TITLE
IllegalArgumentException for cyclic package dependency 

### ISSUE THREAD

**Issue by vaadin-miki** [BasLeijdekkers/MetricsReloaded#36]
Running a scan for `Package metrics` - `Number of cyclic package dependencies` gives an error:

    Argument for @NotNull parameter 'aPackage' of com/sixrr/metrics/metricModel/MetricsRunImpl.postPackageMetric must not be null
    java.lang.IllegalArgumentException: Argument for @NotNull parameter 'aPackage' of com/sixrr/metrics/metricModel/MetricsRunImpl.postPackageMetric must not be null
    at com.sixrr.metrics.metricModel.MetricsRunImpl.postPackageMetric(MetricsRunImpl.java)
    at com.sixrr.stockmetrics.packageCalculators.PackageCalculator.postMetric(PackageCalculator.java:33)
    at com.sixrr.stockmetrics.packageCalculators.NumCyclicDependenciesPackageCalculator.endMetricsRun(NumCyclicDependenciesPackageCalculator.java:38)
    at com.sixrr.metrics.metricModel.MetricsExecutionContextImpl.calculateMetrics(MetricsExecutionContextImpl.java:130)
    at com.sixrr.metrics.metricModel.MetricsExecutionContextImpl$1.run(MetricsExecutionContextImpl.java:62)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:710)

A typical maven project; Java 8, IntelliJ IDEA 2016.3.2, running Win10 Pro (all 64 bit).

**Comment by vaadin-miki** [comment]
Some other cyclic metrics result also in an error, no idea if it is possibly related, for example `Interface metrics` - `Number of cyclic dependencies` (or `Class metrics`, for that matter) gives this error:
    null
    java.lang.NullPointerException
    at com.sixrr.stockmetrics.interfaceCalculators.NumCyclicDependenciesInterfaceCalculator$Visitor.visitClass(NumCyclicDependenciesInterfaceCalculator.java:40)
    at com.intellij.psi.impl.source.PsiClassImpl.accept(PsiClassImpl.java:473)
