### ISSUE TITLE
java.lang.NoSuchFieldError exception when trying to get LOC metrics

### ISSUE THREAD

**Issue by kukido** [BasLeijdekkers/MetricsReloaded#42]
Tried to run on the project, got exception below.

```
SCALA_FILE_TYPE
java.lang.NoSuchFieldError: SCALA_FILE_TYPE
	at com.sixrr.stockmetrics.projectMetrics.LinesOfScalaProjectMetric.createCalculator(LinesOfScalaProjectMetric.java:49)
	at com.sixrr.metrics.metricModel.MetricsExecutionContextImpl.calculateMetrics(MetricsExecutionContextImpl.java:91)
	at com.sixrr.metrics.metricModel.MetricsExecutionContextImpl$1.run(MetricsExecutionContextImpl.java:62)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:726)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:137)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by krishnanmms** [comment]
Workaround : Disabling/uninstalling SCALA plugin in Intellij fixes this problem

**Comment by wherkamp** [comment]
I just had the same issue.

**Comment by bbecker-te** [comment]
But I would like to run metricsReloaded on my scala project. Can I do it without disabling/removing the scala plugin?
