### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by leventov** [BasLeijdekkers/MetricsReloaded#45]
```
SCALA_FILE_TYPE
java.lang.NoSuchFieldError: SCALA_FILE_TYPE
	at com.sixrr.stockmetrics.projectMetrics.LinesOfScalaProjectMetric.createCalculator(LinesOfScalaProjectMetric.java:49)
	at com.sixrr.metrics.metricModel.MetricsExecutionContextImpl.calculateMetrics(MetricsExecutionContextImpl.java:91)
	at com.sixrr.metrics.metricModel.MetricsExecutionContextImpl$1.run(MetricsExecutionContextImpl.java:62)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:726)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:137)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by BasLeijdekkers** [comment]
duplicates #42
