### ISSUE TITLE
org.picocontainer.defaults.DuplicateComponentKeyRegistrationException

### ISSUE THREAD

**Issue by zeecitizen** [BasLeijdekkers/MetricsReloaded#53]
Following error stops IntelliJ from starting up on Windows.  

`Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\MZeeshan>"C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1\bin\idea.bat"
org.picocontainer.defaults.DuplicateComponentKeyRegistrationException: Key com.sixrr.metrics.config.MetricsReloadedConfig duplicated
        at com.intellij.util.pico.DefaultPicoContainer.registerComponent(DefaultPicoContainer.java:137)
        at com.intellij.openapi.components.impl.ServiceManagerImpl$1.extensionAdded(ServiceManagerImpl.java:92)
        at com.intellij.openapi.components.impl.ServiceManagerImpl$1.extensionAdded(ServiceManagerImpl.java:70)
        at com.intellij.openapi.extensions.impl.ExtensionPointImpl.addExtensionPointListener(ExtensionPointImpl.java:405)
        at com.intellij.openapi.components.impl.ServiceManagerImpl.installEP(ServiceManagerImpl.java:101)
        at com.intellij.openapi.components.impl.ServiceManagerImpl.<init>(ServiceManagerImpl.java:54)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
        at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:103)
        at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:80)
        at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
        at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:459)
        at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:240)
        at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:207)
        at com.intellij.openapi.application.impl.ApplicationImpl.lambda$load$8(ApplicationImpl.java:398)
        at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:88)
        at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:396)
        at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:382)
        at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:195)
        at com.intellij.idea.MainImpl$1.lambda$null$0(MainImpl.java:49)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
        at java.awt.EventQueue.access$500(EventQueue.java:98)
        at java.awt.EventQueue$3.run(EventQueue.java:715)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:413)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
org.picocontainer.defaults.DuplicateComponentKeyRegistrationException: Key com.sixrr.metrics.profile.MetricsProfileRepository duplicated
        at com.intellij.util.pico.DefaultPicoContainer.registerComponent(DefaultPicoContainer.java:137)
        at com.intellij.openapi.components.impl.ServiceManagerImpl$1.extensionAdded(ServiceManagerImpl.java:92)
        at com.intellij.openapi.components.impl.ServiceManagerImpl$1.extensionAdded(ServiceManagerImpl.java:70)
        at com.intellij.openapi.extensions.impl.ExtensionPointImpl.addExtensionPointListener(ExtensionPointImpl.java:405)
        at com.intellij.openapi.components.impl.ServiceManagerImpl.installEP(ServiceManagerImpl.java:101)
        at com.intellij.openapi.components.impl.ServiceManagerImpl.<init>(ServiceManagerImpl.java:54)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
        at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:103)
        at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:80)
        at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
        at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:459)
        at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:240)
        at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:207)
        at com.intellij.openapi.application.impl.ApplicationImpl.lambda$load$8(ApplicationImpl.java:398)
        at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:88)
        at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:396)
        at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:382)
        at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:195)
        at com.intellij.idea.MainImpl$1.lambda$null$0(MainImpl.java:49)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
        at java.awt.EventQueue.access$500(EventQueue.java:98)
        at java.awt.EventQueue$3.run(EventQueue.java:715)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:413)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
org.picocontainer.defaults.DuplicateComponentKeyRegistrationException: Key com.sixrr.metrics.ui.metricdisplay.MetricsToolWindow duplicated
        at com.intellij.util.pico.DefaultPicoContainer.registerComponent(DefaultPicoContainer.java:137)
        at com.intellij.openapi.components.impl.ServiceManagerImpl$1.extensionAdded(ServiceManagerImpl.java:92)
        at com.intellij.openapi.components.impl.ServiceManagerImpl$1.extensionAdded(ServiceManagerImpl.java:70)
        at com.intellij.openapi.extensions.impl.ExtensionPointImpl.addExtensionPointListener(ExtensionPointImpl.java:405)
        at com.intellij.openapi.components.impl.ServiceManagerImpl.installEP(ServiceManagerImpl.java:101)
        at com.intellij.openapi.components.impl.ServiceManagerImpl.<init>(ServiceManagerImpl.java:58)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
        at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:103)
        at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:80)
        at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
        at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:459)
        at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:106)
        at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:90)
        at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:77)
        at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:262)
        at com.intellij.openapi.project.impl.ProjectManagerImpl.initProject(ProjectManagerImpl.java:274)
        at com.intellij.openapi.project.impl.ProjectManagerImpl.lambda$getDefaultProject$4(ProjectManagerImpl.java:337)
        at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:185)
        at com.intellij.openapi.project.impl.ProjectManagerImpl.getDefaultProject(ProjectManagerImpl.java:334)
        at com.intellij.ide.fileTemplates.FileTemplateManager.getDefaultInstance(FileTemplateManager.java:66)
        at com.intellij.ide.fileTemplates.FileTemplateManager.getInstance(FileTemplateManager.java:62)
        at com.dci.intellij.dbn.DatabaseNavigator.initComponent(DatabaseNavigator.java:60)
        at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:483)
        at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:106)
        at com.intellij.openapi.application.impl.ApplicationImpl.lambda$createComponents$9(ApplicationImpl.java:437)
        at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
        at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
        at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
        at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:444)
        at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:90)
        at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:396)
        at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:382)
        at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:195)
        at com.intellij.idea.MainImpl$1.lambda$null$0(MainImpl.java:49)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
        at java.awt.EventQueue.access$500(EventQueue.java:98)
        at java.awt.EventQueue$3.run(EventQueue.java:715)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:413)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
ERROR - [UNKNOWN] undefined object type: MINING MODEL
DEBUG - [ORACLE-SQL] undefined element type: xml_type_column_properties
DEBUG - [ORACLE-SQL] undefined element type: alter_external_table_clauses
DEBUG - [ORACLE-SQL] undefined element type: records_per_block_clause
DEBUG - [ORACLE-SQL] undefined element type: ref_attribute
DEBUG - [ORACLE-SQL] undefined element type: physical_properties
DEBUG - [ORACLE-SQL] undefined element type: redo_logfile_spec
DEBUG - [ORACLE-SQL] undefined element type: row_movement_clause
DEBUG - [ORACLE-SQL] undefined element type: hash_subpartition_quantity
DEBUG - [ORACLE-SQL] undefined element type: primary_operator
DEBUG - [ORACLE-SQL] undefined element type: parameter_types
DEBUG - [ORACLE-SQL] undefined element type: partition_value
DEBUG - [ORACLE-SQL] undefined element type: lob_partition_storage
DEBUG - [ORACLE-SQL] undefined element type: create_cluster
DEBUG - [ORACLE-SQL] undefined element type: index_attributes
DEBUG - [ORACLE-SQL] undefined element type: parameter_type
DEBUG - [ORACLE-SQL] undefined element type: return_type
DEBUG - [ORACLE-SQL] undefined element type: scn_value
DEBUG - [ORACLE-SQL] undefined element type: move_table_clause
DEBUG - [ORACLE-SQL] undefined element type: data_item
DEBUG - [ORACLE-SQL] undefined element type: create_index_statement
Terminate batch job (Y/N)? Y

C:\Users\MZeeshan>"C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1\bin\idea.bat"
org.picocontainer.defaults.DuplicateComponentKeyRegistrationException: Key com.sixrr.metrics.config.MetricsReloadedConfig duplicated
        at com.intellij.util.pico.DefaultPicoContainer.registerComponent(DefaultPicoContainer.java:137)
        at com.intellij.openapi.components.impl.ServiceManagerImpl$1.extensionAdded(ServiceManagerImpl.java:92)
        at com.intellij.openapi.components.impl.ServiceManagerImpl$1.extensionAdded(ServiceManagerImpl.java:70)
        at com.intellij.openapi.extensions.impl.ExtensionPointImpl.addExtensionPointListener(ExtensionPointImpl.java:405)
        at com.intellij.openapi.components.impl.ServiceManagerImpl.installEP(ServiceManagerImpl.java:101)
        at com.intellij.openapi.components.impl.ServiceManagerImpl.<init>(ServiceManagerImpl.java:54)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
        at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:103)
        at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:80)
        at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
        at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:459)
        at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:240)
        at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:207)
        at com.intellij.openapi.application.impl.ApplicationImpl.lambda$load$8(ApplicationImpl.java:398)
        at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:88)
        at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:396)
        at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:382)
        at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:195)
        at com.intellij.idea.MainImpl$1.lambda$null$0(MainImpl.java:49)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
        at java.awt.EventQueue.access$500(EventQueue.java:98)
        at java.awt.EventQueue$3.run(EventQueue.java:715)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:413)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
org.picocontainer.defaults.DuplicateComponentKeyRegistrationException: Key com.sixrr.metrics.profile.MetricsProfileRepository duplicated
        at com.intellij.util.pico.DefaultPicoContainer.registerComponent(DefaultPicoContainer.java:137)
        at com.intellij.openapi.components.impl.ServiceManagerImpl$1.extensionAdded(ServiceManagerImpl.java:92)
        at com.intellij.openapi.components.impl.ServiceManagerImpl$1.extensionAdded(ServiceManagerImpl.java:70)
        at com.intellij.openapi.extensions.impl.ExtensionPointImpl.addExtensionPointListener(ExtensionPointImpl.java:405)
        at com.intellij.openapi.components.impl.ServiceManagerImpl.installEP(ServiceManagerImpl.java:101)
        at com.intellij.openapi.components.impl.ServiceManagerImpl.<init>(ServiceManagerImpl.java:54)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
        at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:103)
        at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:80)
        at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
        at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:459)
        at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:240)
        at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:207)
        at com.intellij.openapi.application.impl.ApplicationImpl.lambda$load$8(ApplicationImpl.java:398)
        at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:88)
        at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:396)
        at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:382)
        at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:195)
        at com.intellij.idea.MainImpl$1.lambda$null$0(MainImpl.java:49)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
        at java.awt.EventQueue.access$500(EventQueue.java:98)
        at java.awt.EventQueue$3.run(EventQueue.java:715)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:413)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
org.picocontainer.defaults.DuplicateComponentKeyRegistrationException: Key com.sixrr.metrics.ui.metricdisplay.MetricsToolWindow duplicated
        at com.intellij.util.pico.DefaultPicoContainer.registerComponent(DefaultPicoContainer.java:137)
        at com.intellij.openapi.components.impl.ServiceManagerImpl$1.extensionAdded(ServiceManagerImpl.java:92)
        at com.intellij.openapi.components.impl.ServiceManagerImpl$1.extensionAdded(ServiceManagerImpl.java:70)
        at com.intellij.openapi.extensions.impl.ExtensionPointImpl.addExtensionPointListener(ExtensionPointImpl.java:405)
        at com.intellij.openapi.components.impl.ServiceManagerImpl.installEP(ServiceManagerImpl.java:101)
        at com.intellij.openapi.components.impl.ServiceManagerImpl.<init>(ServiceManagerImpl.java:58)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
        at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:103)
        at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:80)
        at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
        at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:459)
        at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:106)
        at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:90)
        at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:77)
        at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:262)
        at com.intellij.openapi.project.impl.ProjectManagerImpl.initProject(ProjectManagerImpl.java:274)
        at com.intellij.openapi.project.impl.ProjectManagerImpl.lambda$getDefaultProject$4(ProjectManagerImpl.java:337)
        at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:185)
        at com.intellij.openapi.project.impl.ProjectManagerImpl.getDefaultProject(ProjectManagerImpl.java:334)
        at com.intellij.ide.fileTemplates.FileTemplateManager.getDefaultInstance(FileTemplateManager.java:66)
        at com.intellij.ide.fileTemplates.FileTemplateManager.getInstance(FileTemplateManager.java:62)
        at com.dci.intellij.dbn.DatabaseNavigator.initComponent(DatabaseNavigator.java:60)
        at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:483)
        at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:106)
        at com.intellij.openapi.application.impl.ApplicationImpl.lambda$createComponents$9(ApplicationImpl.java:437)
        at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
        at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
        at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
        at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:444)
        at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:90)
        at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:396)
        at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:382)
        at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:195)
        at com.intellij.idea.MainImpl$1.lambda$null$0(MainImpl.java:49)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
        at java.awt.EventQueue.access$500(EventQueue.java:98)
        at java.awt.EventQueue$3.run(EventQueue.java:715)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:413)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
ERROR - [UNKNOWN] undefined object type: MINING MODEL
DEBUG - [ORACLE-SQL] undefined element type: xml_type_column_properties
DEBUG - [ORACLE-SQL] undefined element type: alter_external_table_clauses
DEBUG - [ORACLE-SQL] undefined element type: records_per_block_clause
DEBUG - [ORACLE-SQL] undefined element type: ref_attribute
DEBUG - [ORACLE-SQL] undefined element type: physical_properties
DEBUG - [ORACLE-SQL] undefined element type: redo_logfile_spec
DEBUG - [ORACLE-SQL] undefined element type: row_movement_clause
DEBUG - [ORACLE-SQL] undefined element type: hash_subpartition_quantity
DEBUG - [ORACLE-SQL] undefined element type: primary_operator
DEBUG - [ORACLE-SQL] undefined element type: parameter_types
DEBUG - [ORACLE-SQL] undefined element type: partition_value
DEBUG - [ORACLE-SQL] undefined element type: lob_partition_storage
DEBUG - [ORACLE-SQL] undefined element type: create_cluster
DEBUG - [ORACLE-SQL] undefined element type: index_attributes
DEBUG - [ORACLE-SQL] undefined element type: parameter_type
DEBUG - [ORACLE-SQL] undefined element type: return_type
DEBUG - [ORACLE-SQL] undefined element type: scn_value
DEBUG - [ORACLE-SQL] undefined element type: move_table_clause
DEBUG - [ORACLE-SQL] undefined element type: data_item
DEBUG - [ORACLE-SQL] undefined element type: create_index_statement
`

**Comment by BasLeijdekkers** [comment]
I can't reproduce this. Is there any more info you can provide? Which other plugins do you have installed for example?
