### ISSUE TITLE
Dependency Metrics Crash

### ISSUE THREAD

**Issue by Pluriscient** [BasLeijdekkers/MetricsReloaded#54]
When running the Dependency Metrics for our `entire project`, the plugin crashes with the attached stacktrace, though it does run other metrics, as well as for individual files.
```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'aPackage' of com/sixrr/metrics/metricModel/MetricsRunImpl.postPackageMetric must not be null
	at com.sixrr.metrics.metricModel.MetricsRunImpl.postPackageMetric(MetricsRunImpl.java)
	at com.sixrr.stockmetrics.packageCalculators.PackageCalculator.postMetric(PackageCalculator.java:29)
	at com.sixrr.stockmetrics.packageCalculators.NumDependentPackagesPackageCalculator.endMetricsRun(NumDependentPackagesPackageCalculator.java:38)
	at com.sixrr.metrics.metricModel.MetricsExecutionContextImpl.calculateMetrics(MetricsExecutionContextImpl.java:130)
	at com.sixrr.metrics.metricModel.MetricsExecutionContextImpl$1.run(MetricsExecutionContextImpl.java:62)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:736)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by benedikt257** [comment]
I am observing the same issue. 

Here is some information about the IntelliJ version I am running and my machine:
IntelliJ IDEA 2018.2.5 (Ultimate Edition)
Build #IU-182.4892.20, built on October 16, 2018
JRE: 1.8.0_152-release-1248-b19 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

I am of course running version 1.8 of the MetricsReloaded plug-in.

**Comment by kirki333** [comment]
I have the same issue.
IntelliJ IDEA 2017.3.6 (Community Edition)
Build #IC-173.4674.60, built on November 13, 2018
JRE: 1.8.0_152-release-1024-b18 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10  Home
