### ISSUE TITLE
org.picocontainer.defaults.DuplicateComponentKeyRegistrationException

### ISSUE THREAD

**Issue by gvespucci** [BasLeijdekkers/MetricsReloaded#56]
IDEA crashes at the startup. It only shows the splash screen.
MetricsReloaded 1.8
IntelliJ IDEA 2019.1.1  Build #IU-191.6707.61
JDK: 1.8.0_202-release; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o
OS: Mac OS X

```
2019-04-26 16:33:37,082 [   4289]  ERROR - llij.ide.plugins.PluginManager - com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing 'com.intellij.openapi.components.impl.ServiceManagerImpl' 
java.lang.RuntimeException: com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing 'com.intellij.openapi.components.impl.ServiceManagerImpl'
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:215)
	at com.intellij.idea.IdeaApplication.lambda$initApplication$0(IdeaApplication.java:74)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:347)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing 'com.intellij.openapi.components.impl.ServiceManagerImpl'
	at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:256)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.handleInitComponentError(PlatformComponentManagerImpl.java:43)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:500)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:246)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:213)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$load$8(ApplicationImpl.java:409)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:86)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:407)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:393)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:208)
	... 16 more
Caused by: org.picocontainer.defaults.DuplicateComponentKeyRegistrationException: Key com.sixrr.metrics.config.MetricsReloadedConfig duplicated
	at com.intellij.util.pico.DefaultPicoContainer.registerComponent(DefaultPicoContainer.java:123)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$1.extensionAdded(ServiceManagerImpl.java:77)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$1.extensionAdded(ServiceManagerImpl.java:63)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.notifyListenersAboutLoadedExtensions(ExtensionPointImpl.java:659)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.addExtensionPointListener(ExtensionPointImpl.java:603)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.addExtensionPointListener(ExtensionPointImpl.java:570)
	at com.intellij.openapi.components.impl.ServiceManagerImpl.installEP(ServiceManagerImpl.java:63)
	at com.intellij.openapi.components.impl.ServiceManagerImpl.<init>(ServiceManagerImpl.java:46)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:92)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:66)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:48)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:458)
	... 23 more
2019-04-26 16:33:37,084 [   4291]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 2019.1.1  Build #IU-191.6707.61 
2019-04-26 16:33:37,084 [   4291]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_202-release; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2019-04-26 16:33:37,084 [   4291]  ERROR - llij.ide.plugins.PluginManager - OS: Mac OS X 
2019-04-26 16:35:29,101 [ 116308]   INFO -        #com.intellij.idea.Main - ------------------------------------------------------ IDE SHUTDOWN ------------------------------------------------------ 
2019-04-26 16:35:29,105 [ 116312]   INFO - org.jetbrains.io.BuiltInServer - web server stopped 

```

**Comment by gvespucci** [comment]
@zeecitizen, any news on issue https://github.com/BasLeijdekkers/MetricsReloaded/issues/53, just in case? Thank you very much.

**Comment by BasLeijdekkers** [comment]
The plugin files should be in ~/Library/Application Support/IntelliJIDEA2019.1/MetricsReloaded. Do you have any other downloaded plugins installed?

**Comment by gvespucci** [comment]
Hi, I've just removed the folder where you suggest me and luckily IDEA started again...  I have other plugins installed, such as Material and others, but looks clear at this point that MetricsReloaded clashed with some other things...

**Comment by BasLeijdekkers** [comment]
Yes, but it would be nice to know which plugin it clashes with. I, of course, have MetricsReloaded installed myself and never experienced this problem.

**Comment by gvespucci** [comment]
I see your point @BasLeijdekkers. The plugins I have at the moment in the "Installed" sections are:

- ANSI Highligther
- BashSupport
- CheckStyle-IDEA
- CSV Plugin
- EduTools
- HOCON 
- IDE Features Trainer
- Ideolog
- Infinitest
- Kotlin
- Lombok
- Material Theme UI
- Save Actions

**Comment by BasLeijdekkers** [comment]
duplicates $53
