### ISSUE TITLE
Calculate Metrics (1.11.1) - Lines of code (System profile) results in java.lang.NullPointerException

### ISSUE THREAD

**Issue by denysobukh** [BasLeijdekkers/MetricsReloaded#70]
```
java.lang.NullPointerException
	at com.sixrr.stockmetrics.utils.LineUtil.countLines(LineUtil.java:42)
	at com.sixrr.stockmetrics.utils.LineUtil.countLines(LineUtil.java:36)
	at com.sixrr.stockmetrics.interfaceCalculators.SourceLinesOfCodeInterfaceCalculator$Visitor.visitClass(SourceLinesOfCodeInterfaceCalculator.java:52)
	at com.intellij.psi.impl.source.PsiClassImpl.accept(PsiClassImpl.java:459)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:185)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:754)
	at com.intellij.psi.JavaRecursiveElementVisitor.visitElement(JavaRecursiveElementVisitor.java:44)
	at com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:35)
	at com.intellij.psi.JavaElementVisitor.visitJavaFile(JavaElementVisitor.java:340)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.accept(PsiJavaFileBaseImpl.java:472)
	at com.sixrr.stockmetrics.execution.BaseMetricsCalculator.lambda$processFile$0(BaseMetricsCalculator.java:67)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.sixrr.stockmetrics.execution.BaseMetricsCalculator.processFile(BaseMetricsCalculator.java:67)
	at com.sixrr.metrics.metricModel.MetricsExecutionContextImpl$2.visitFile(MetricsExecutionContextImpl.java:120)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.accept(PsiJavaFileBaseImpl.java:475)
	at com.intellij.analysis.AnalysisScope.doProcessFile(AnalysisScope.java:421)
	at com.intellij.analysis.AnalysisScope.lambda$processFile$7(AnalysisScope.java:368)
	at com.intellij.analysis.AnalysisScope.lambda$commitAndRunInSmartMode$8(AnalysisScope.java:384)
	at com.intellij.psi.impl.PsiDocumentManagerBase.lambda$commitAndRunReadAction$8(PsiDocumentManagerBase.java:504)
	at com.intellij.psi.impl.PsiDocumentManagerBase.lambda$commitAndRunReadAction$9(PsiDocumentManagerBase.java:529)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:889)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.psi.impl.PsiDocumentManagerBase.commitAndRunReadAction(PsiDocumentManagerBase.java:527)
	at com.intellij.psi.impl.PsiDocumentManagerBase.commitAndRunReadAction(PsiDocumentManagerBase.java:504)
	at com.intellij.analysis.AnalysisScope.commitAndRunInSmartMode(AnalysisScope.java:382)
	at com.intellij.analysis.AnalysisScope.processFile(AnalysisScope.java:368)
```

**Comment by leobastiani** [comment]
Same here

**Comment by BasLeijdekkers** [comment]
An update with a fix for this issue is now available.
