### ISSUE TITLE
Crashed on attempt to calculate metrics

### ISSUE THREAD

**Issue by Alexsey** [BasLeijdekkers/MetricsReloaded#73]
I have tried all 3 of "Whole project", "File ..." and "Scope" and both "Lines of code metrics" and "Number of files metrics" - none is working :(

I didn't set the checkbox "Show only results which exceed metrics threshold"

```
WebStorm 2021.2 EAP
Build #WS-212.4638.10, built on July 7, 2021
WebStorm EAP User
Runtime version: 11.0.11+9-b1504.8 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.4
GC: ParNew, ConcurrentMarkSweep
Memory: 6255M
Cores: 16
Registry: debugger.watches.in.variables=false, ide.mac.file.chooser.native=false, ide.mac.native.save.dialog=false, ide.mac.inplaceDialogMnemonicsFix=true, js.debugger.webconsole=false
Non-Bundled Plugins: String Manipulation (8.15.203.000.3), com.andreycizov.partialnav (1.3), com.fwdekker.randomness (2.7.2), com.intellij.microservices.ui (212.4638.10), com.mnw.tabmover (1.3.0), org.nik.presentation-assistant (1.0.9), quokka.js (1.0.304), wallaby.js (1.0.216), com.vladsch.idea.multimarkdown (3.0.202.112), lermitage.intellij.extra.icons (1.57.0.203), MetricsReloaded (1.11.2), com.intellij.database (212.4638.10), izhangzhihao.rainbow.brackets (6.18)
```

```java.lang.NoClassDefFoundError: com/intellij/ide/highlighter/NewJspFileType
	at com.sixrr.stockmetrics.projectMetrics.LinesOfJSPProjectMetric.createCalculator(LinesOfJSPProjectMetric.java:49)
	at com.sixrr.metrics.metricModel.MetricsExecutionContextImpl.calculateMetrics(MetricsExecutionContextImpl.java:90)
	at com.sixrr.metrics.metricModel.MetricsExecutionContextImpl$1.run(MetricsExecutionContextImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:450)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:117)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:510)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:243)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:243)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: com.intellij.ide.highlighter.NewJspFileType PluginClassLoader(plugin=PluginDescriptor(name=MetricsReloaded, id=MetricsReloaded, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/WebStorm2021.2/plugins/MetricsReloaded, version=1.11.2, package=null), packagePrefix=null, instanceId=95, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:254)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 21 more
```

**Comment by BasLeijdekkers** [comment]
Workaround until this fixed: disable the Java Server Pages plugin.

**Comment by Alexsey** [comment]
Thank you, the workaround works!
