### ISSUE TITLE
Crash on attempt to calculate "Number of files metrics"

### ISSUE THREAD

**Issue by Alexsey** [BasLeijdekkers/MetricsReloaded#78]
It's the first time I've tried to run the plugin for the project and it crashed

STR:
1. Actions -> Calculate Metrics...
2. Metrics Scope - Custom scope: <scope with TypeScript, SQL and JSON files>
3. Metrics Profile - Number of files metrics
4. "Show only results which exceed metric thresholds" - unchecked
5. Press **Analyze** button

Notes:
 * The first time it crashed with the stacktrace
 * On future attempts, after pressing **Analize** button, the popup is getting closed with nothing happening
 * I have tried to change Metrics Scope to different options - non of them is working
 * Number of lines analytic is working well

<details>
<summary>Stacktrace</summary>

```
com.intellij.diagnostic.PluginException: Cannot load class com.sixrr.stockmetrics.projectCalculators.NumModulesInProjectCalculator$Visitor (
  error: com/intellij/psi/JavaRecursiveElementVisitor,
  classLoader=PluginClassLoader(plugin=PluginDescriptor(name=MetricsReloaded, id=MetricsReloaded, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/WebStorm2022.2/plugins/MetricsReloaded, version=1.12, package=null, isBundled=false), packagePrefix=null, instanceId=127, state=active)
)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:406)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:234)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:206)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at com.sixrr.stockmetrics.projectMetrics.NumModulesInProjectMetric.createCalculator(NumModulesInProjectMetric.java:46)
	at com.sixrr.metrics.metricModel.MetricsExecutionContextImpl.calculateMetrics(MetricsExecutionContextImpl.java:90)
	at com.sixrr.metrics.metricModel.MetricsExecutionContextImpl$1.run(MetricsExecutionContextImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NoClassDefFoundError: com/intellij/psi/JavaRecursiveElementVisitor
	at java.base/java.lang.ClassLoader.defineClass2(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1103)
	at com.intellij.util.lang.UrlClassLoader.consumeClassData(UrlClassLoader.java:253)
	at com.intellij.util.lang.ZipResourceFile.findClass(ZipResourceFile.java:114)
	at com.intellij.util.lang.JarLoader.findClass(JarLoader.java:63)
	at com.intellij.util.lang.ClassPath.findClassInLoader(ClassPath.java:246)
	at com.intellij.util.lang.ClassPath.findClass(ClassPath.java:179)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:398)
	... 26 more
Caused by: java.lang.ClassNotFoundException: com.intellij.psi.JavaRecursiveElementVisitor PluginClassLoader(plugin=PluginDescriptor(name=MetricsReloaded, id=MetricsReloaded, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/WebStorm2022.2/plugins/MetricsReloaded, version=1.12, package=null, isBundled=false), packagePrefix=null, instanceId=127, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:209)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 34 more
```
</details>

<details>
<summary>System & IDE</summary>

```
WebStorm 2022.2 EAP
Build #WS-222.2889.12, built on June 2, 2022
Licensed to WebStorm EAP user: Oleksii Bobyr
Expiration date: July 2, 2022
Runtime version: 17.0.3+7-b463.3 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.4
GC: G1 Young Generation, G1 Old Generation
Memory: 4128M
Cores: 10
Metal Rendering is ON
Registry:
    debugger.watches.in.variables=false
    ide.mac.file.chooser.native=false
    ide.mac.native.save.dialog=false
    ide.mac.inplaceDialogMnemonicsFix=true
    js.debugger.webconsole=false

Non-Bundled Plugins:
    wallaby.js (1.0.239)
    socrates.tabshifter (0.30)
    quokka.js (1.0.342)
    org.toml.lang (222.2889.12)
    org.para.plugin.openInSplittedTab (0.2)
    org.nik.presentation-assistant (1.0.9)
    me.serce.solidity (2.3.9)
    com.mnw.tabmover (1.4.1)
    com.intellij.ideolog (203.0.30.0)
    com.intellij.microservices.ui (222.2889.12)
    com.fwdekker.randomness (2.7.5)
    au.com.glassechidna.luanalysis (1.2.2-IDEA203)
    String Manipulation (9.4.1)
    mobi.hsz.idea.gitignore (4.4.1)
    com.intellij.database (222.2889.12)
    izhangzhihao.rainbow.brackets (6.24)
    MetricsReloaded (1.12)
    org.asciidoctor.intellij.asciidoc (0.37.19)
    ru.adelf.idea.dotenv (2022.2)
    lermitage.intellij.extra.icons (2022.1.4)
```
</details>

**Comment by nickQuant** [comment]
Similar issue experienced in Rider 2022.2

com.intellij.diagnostic.PluginException: Cannot load class com.sixrr.stockmetrics.projectCalculators.NumModulesInProjectCalculator$Visitor (
  error: com/intellij/psi/JavaRecursiveElementVisitor,
  classLoader=PluginClassLoader(plugin=PluginDescriptor(name=MetricsReloaded, id=MetricsReloaded, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\Rider2022.2\plugins\MetricsReloaded, version=1.12, package=null, isBundled=false), packagePrefix=null, instanceId=109, state=active)
)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:411)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:239)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:211)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at com.sixrr.stockmetrics.projectMetrics.NumModulesInProjectMetric.createCalculator(NumModulesInProjectMetric.java:46)
	at com.sixrr.metrics.metricModel.MetricsExecutionContextImpl.calculateMetrics(MetricsExecutionContextImpl.java:90)
	at com.sixrr.metrics.metricModel.MetricsExecutionContextImpl$1.run(MetricsExecutionContextImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.codeWithMe.ClientId$Companion$decorateFunction$2.apply(ClientId.kt:307)
	at com.intellij.codeWithMe.ClientId$Companion$decorateFunction$2.apply(ClientId.kt:307)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NoClassDefFoundError: com/intellij/psi/JavaRecursiveElementVisitor
	at java.base/java.lang.ClassLoader.defineClass2(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1103)
	at com.intellij.util.lang.UrlClassLoader.consumeClassData(UrlClassLoader.java:253)
	at com.intellij.util.lang.ZipResourceFile.findClass(ZipResourceFile.java:114)
	at com.intellij.util.lang.JarLoader.findClass(JarLoader.java:63)
	at com.intellij.util.lang.ClassPath.findClassInLoader(ClassPath.java:246)
	at com.intellij.util.lang.ClassPath.findClass(ClassPath.java:179)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:403)
	... 28 more
Caused by: java.lang.ClassNotFoundException: com.intellij.psi.JavaRecursiveElementVisitor PluginClassLoader(plugin=PluginDescriptor(name=MetricsReloaded, id=MetricsReloaded, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\Rider2022.2\plugins\MetricsReloaded, version=1.12, package=null, isBundled=false), packagePrefix=null, instanceId=109, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:214)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 36 more
